# TCL File Generated by Component Editor 16.1
# Wed Feb 07 13:58:05 EST 2018
# DO NOT MODIFY


# 
# lda_avalon_interface "VGA Line Drawer" v1.1
#  2018.02.07.13:58:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lda_avalon_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME lda_avalon_interface
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Components"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Line Drawer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lda_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lda_avalon_interface.sv SYSTEM_VERILOG PATH lda/lda_asc/lda_avalon_interface.sv TOP_LEVEL_FILE
add_fileset_file lda_asc_control.sv SYSTEM_VERILOG PATH lda/lda_asc/lda_asc_control.sv
add_fileset_file lda_asc_datapath.sv SYSTEM_VERILOG PATH lda/lda_asc/lda_asc_datapath.sv
add_fileset_file lda_avalon_slave_controller.sv SYSTEM_VERILOG PATH lda/lda_asc/lda_avalon_slave_controller.sv
add_fileset_file lda_control.sv SYSTEM_VERILOG PATH lda/lda/lda_control.sv
add_fileset_file lda_datapath.sv SYSTEM_VERILOG PATH lda/lda/lda_datapath.sv
add_fileset_file line_drawing_algorithm.sv SYSTEM_VERILOG PATH lda/lda/line_drawing_algorithm.sv
add_fileset_file vga_adapter.sdc SDC PATH lda/vga/vga_adapter.sdc
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH lda/vga/vga_adapter.sv
add_fileset_file vga_input.sv SYSTEM_VERILOG PATH lda/vga/vga_input.sv
add_fileset_file vga_memory.sv SYSTEM_VERILOG PATH lda/vga/vga_memory.sv
add_fileset_file vga_output.sv SYSTEM_VERILOG PATH lda/vga/vga_output.sv
add_fileset_file vgapll.v VERILOG PATH lda/vga/vgapll.v
add_fileset_file comparator.sv SYSTEM_VERILOG PATH common/comparator.sv
add_fileset_file simple_alu.sv SYSTEM_VERILOG PATH common/simple_alu.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point lda_avalon_slave
# 
add_interface lda_avalon_slave avalon end
set_interface_property lda_avalon_slave addressUnits WORDS
set_interface_property lda_avalon_slave associatedClock clk
set_interface_property lda_avalon_slave associatedReset reset
set_interface_property lda_avalon_slave bitsPerSymbol 8
set_interface_property lda_avalon_slave burstOnBurstBoundariesOnly false
set_interface_property lda_avalon_slave burstcountUnits WORDS
set_interface_property lda_avalon_slave explicitAddressSpan 32
set_interface_property lda_avalon_slave holdTime 0
set_interface_property lda_avalon_slave linewrapBursts false
set_interface_property lda_avalon_slave maximumPendingReadTransactions 0
set_interface_property lda_avalon_slave maximumPendingWriteTransactions 0
set_interface_property lda_avalon_slave readLatency 0
set_interface_property lda_avalon_slave readWaitTime 1
set_interface_property lda_avalon_slave setupTime 0
set_interface_property lda_avalon_slave timingUnits Cycles
set_interface_property lda_avalon_slave writeWaitTime 0
set_interface_property lda_avalon_slave ENABLED true
set_interface_property lda_avalon_slave EXPORT_OF ""
set_interface_property lda_avalon_slave PORT_NAME_MAP ""
set_interface_property lda_avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property lda_avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port lda_avalon_slave i_byteenable byteenable Input 4
add_interface_port lda_avalon_slave i_chipselect chipselect Input 1
add_interface_port lda_avalon_slave i_read read Input 1
add_interface_port lda_avalon_slave i_write write Input 1
add_interface_port lda_avalon_slave i_writedata writedata Input 32
add_interface_port lda_avalon_slave o_readdata readdata Output 32
add_interface_port lda_avalon_slave o_waitrequest waitrequest Output 1
set_interface_assignment lda_avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment lda_avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment lda_avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment lda_avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk i_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset i_resetn reset_n Input 1


# 
# connection point vga_g_external_connection
# 
add_interface vga_g_external_connection conduit end
set_interface_property vga_g_external_connection associatedClock clk
set_interface_property vga_g_external_connection associatedReset ""
set_interface_property vga_g_external_connection ENABLED true
set_interface_property vga_g_external_connection EXPORT_OF ""
set_interface_property vga_g_external_connection PORT_NAME_MAP ""
set_interface_property vga_g_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_g_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_g_external_connection o_vga_g_export export Output 8


# 
# connection point vga_b_external_connection
# 
add_interface vga_b_external_connection conduit end
set_interface_property vga_b_external_connection associatedClock clk
set_interface_property vga_b_external_connection associatedReset ""
set_interface_property vga_b_external_connection ENABLED true
set_interface_property vga_b_external_connection EXPORT_OF ""
set_interface_property vga_b_external_connection PORT_NAME_MAP ""
set_interface_property vga_b_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_b_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_b_external_connection o_vga_b_export export Bidir 8


# 
# connection point vga_r_external_connection
# 
add_interface vga_r_external_connection conduit end
set_interface_property vga_r_external_connection associatedClock clk
set_interface_property vga_r_external_connection associatedReset ""
set_interface_property vga_r_external_connection ENABLED true
set_interface_property vga_r_external_connection EXPORT_OF ""
set_interface_property vga_r_external_connection PORT_NAME_MAP ""
set_interface_property vga_r_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_r_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_r_external_connection o_vga_r_export export Output 8


# 
# connection point vga_hs_external_connection
# 
add_interface vga_hs_external_connection conduit end
set_interface_property vga_hs_external_connection associatedClock clk
set_interface_property vga_hs_external_connection associatedReset ""
set_interface_property vga_hs_external_connection ENABLED true
set_interface_property vga_hs_external_connection EXPORT_OF ""
set_interface_property vga_hs_external_connection PORT_NAME_MAP ""
set_interface_property vga_hs_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_hs_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_hs_external_connection o_vga_hs_export export Output 1


# 
# connection point vga_vs_external_connection
# 
add_interface vga_vs_external_connection conduit end
set_interface_property vga_vs_external_connection associatedClock clk
set_interface_property vga_vs_external_connection associatedReset ""
set_interface_property vga_vs_external_connection ENABLED true
set_interface_property vga_vs_external_connection EXPORT_OF ""
set_interface_property vga_vs_external_connection PORT_NAME_MAP ""
set_interface_property vga_vs_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_vs_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_vs_external_connection o_vga_vs_export export Output 1


# 
# connection point vga_sync_n_external_connection
# 
add_interface vga_sync_n_external_connection conduit end
set_interface_property vga_sync_n_external_connection associatedClock clk
set_interface_property vga_sync_n_external_connection associatedReset ""
set_interface_property vga_sync_n_external_connection ENABLED true
set_interface_property vga_sync_n_external_connection EXPORT_OF ""
set_interface_property vga_sync_n_external_connection PORT_NAME_MAP ""
set_interface_property vga_sync_n_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_sync_n_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_sync_n_external_connection o_vga_sync_n_export export Output 1


# 
# connection point vga_blank_n_external_connection
# 
add_interface vga_blank_n_external_connection conduit end
set_interface_property vga_blank_n_external_connection associatedClock clk
set_interface_property vga_blank_n_external_connection associatedReset ""
set_interface_property vga_blank_n_external_connection ENABLED true
set_interface_property vga_blank_n_external_connection EXPORT_OF ""
set_interface_property vga_blank_n_external_connection PORT_NAME_MAP ""
set_interface_property vga_blank_n_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_blank_n_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_blank_n_external_connection o_vga_blank_n_export export Output 1


# 
# connection point vga_clk_external_connection
# 
add_interface vga_clk_external_connection conduit end
set_interface_property vga_clk_external_connection associatedClock clk
set_interface_property vga_clk_external_connection associatedReset ""
set_interface_property vga_clk_external_connection ENABLED true
set_interface_property vga_clk_external_connection EXPORT_OF ""
set_interface_property vga_clk_external_connection PORT_NAME_MAP ""
set_interface_property vga_clk_external_connection CMSIS_SVD_VARIABLES ""
set_interface_property vga_clk_external_connection SVD_ADDRESS_GROUP ""

add_interface_port vga_clk_external_connection o_vga_clk_export export Output 1

